apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
  name: camunda-json-logging-7.11.0
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    pushSecret:
      name: nexus-dev
    to:
      kind: DockerImage
      name: 'pub-registry.dev.witcom.services/witcom/camunda-json-logging:7.11.0'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /tomcat/7.11.0/docker
    git:
      uri: 'https://github.com/iceman91176/container-toolbox'
    type: Git
  strategy:
    dockerStrategy:
      noCache: true
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - github:
        secret: 084vV8mJTy2RJemdRts0D
      type: GitHub
    - generic:
        secret: pm5lN5VmXLBjwRItWux9
      type: Generic
    - type: ConfigChange
    - imageChange:
      type: ImageChange
status:
